//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_18034
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Presentation.
    /// </summary>
    // *** Start programmer edit section *** (Presentation CustomAttributes)

    // *** End programmer edit section *** (Presentation CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MyPresentation", new string[] {
            "Date",
            "Book.Author",
            "Book.Pages",
            "Book.Title"})]
    [View("PresentationE", new string[] {
            "Date as \'Date\'",
            "Book as \'Book\'",
            "Book.Title as \'Title\'"}, Hidden=new string[] {
            "Book.Title"})]
    [MasterViewDefineAttribute("PresentationE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Title")]
    [View("PresentationL", new string[] {
            "Date as \'Дата\'",
            "Book.Title as \'Книга\'",
            "Book.Author as \'Автор\'"})]
    public class Presentation : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fDate;

        private IIS.Product_18034.Book fBook;

        // *** Start programmer edit section *** (Presentation CustomMembers)

        // *** End programmer edit section *** (Presentation CustomMembers)


        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Date CustomAttributes)

        // *** End programmer edit section *** (Presentation.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Date Get start)

                // *** End programmer edit section *** (Presentation.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Presentation.Date Get end)

                // *** End programmer edit section *** (Presentation.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Date Set start)

                // *** End programmer edit section *** (Presentation.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Presentation.Date Set end)

                // *** End programmer edit section *** (Presentation.Date Set end)
            }
        }

        /// <summary>
        /// Presentation.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Book CustomAttributes)

        // *** End programmer edit section *** (Presentation.Book CustomAttributes)
        [PropertyStorage(new string[] {
                "Book"})]
        [NotNull()]
        public virtual IIS.Product_18034.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Book Get start)

                // *** End programmer edit section *** (Presentation.Book Get start)
                IIS.Product_18034.Book result = this.fBook;
                // *** Start programmer edit section *** (Presentation.Book Get end)

                // *** End programmer edit section *** (Presentation.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Book Set start)

                // *** End programmer edit section *** (Presentation.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (Presentation.Book Set end)

                // *** End programmer edit section *** (Presentation.Book Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "MyPresentation" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MyPresentation
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MyPresentation", typeof(IIS.Product_18034.Presentation));
                }
            }

            /// <summary>
            /// "PresentationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PresentationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PresentationE", typeof(IIS.Product_18034.Presentation));
                }
            }

            /// <summary>
            /// "PresentationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PresentationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PresentationL", typeof(IIS.Product_18034.Presentation));
                }
            }
        }
    }
}

